### ISSUE TITLE
CSS FAQs

### ISSUE THREAD

**Issue by hexcola** [hexcola/note#109]
# CSS FAQs

- [How to override Safari default input(button) style](http://www.stepday.com/topic/?1000)

```css
.btn{
  background:#eee;
  border-radius:5px;
  -webkit-appearance: none;/*chrome 与safari*/
  -moz-appearance: none;/*firefox*/
   appearance: none;/*其他浏览器*/
}
```
