### ISSUE TITLE
jQuery and bootstrap

### ISSUE THREAD

**Issue by hexcola** [hexcola/note#202]
## Bootstrap

- **修改 modal 宽度**

```css
.modal{
  width: 750px;
  margin: auto;
}
```

## jQuery 与 Bootstrap 交互

- **如何操作 Modal**

```js
$('#myModal').modal('toggle');
$('#myModal').modal('show');
$('#myModal').modal('hide');
```
参考: [How to open a Bootstrap modal window using jQuery?](https://stackoverflow.com/a/13183713/5176750)
